-- The team's weekly cleaning schedule, as of Oct 2026 (one row per person and task; days 0 = Monday).
insert into public.cleaning_tasks (area, task, days, time_slot, assignee, position) values
('Arkadia','Arkadia (1.5h)',array[0,2]::smallint[],'Early morning','Regi',0),
('Gym','Gym (30 min)',array[0]::smallint[],'Early morning','Regi',1),
('Beehive','Beehive',array[0]::smallint[],'Late morning','Regi',102),
('Deck','Deck y baños',array[0]::smallint[],'Late morning','Regi',103),
('Laundry','Lavandería',array[0]::smallint[],'Afternoon','Regi',204),
('The Ark House','The Ark House (2h)',array[1,3,4]::smallint[],'Early morning','Regi',5),
('Beehive','Beehive chequeo general (3h)',array[1]::smallint[],'Late morning','Regi',106),
('Baños','Baños',array[1]::smallint[],'Late morning','Regi',107),
('Beehive','Cerrar beehives',array[1]::smallint[],'Afternoon','Regi',208),
('Basurero','Basurero',array[2]::smallint[],'Early morning','Regi',10),
('La Sierra','La Sierra - Trailer (3.5h)',array[2]::smallint[],'Late morning','Regi',111),
('The Ark House','Repaso Ark House (1h)',array[2,3]::smallint[],'Afternoon','Regi',212),
('Beehive','Beehive y deck (3h)',array[3]::smallint[],'Late morning','Regi',114),
('Baños','Baños, repaso (30 min)',array[3,4]::smallint[],'Late morning','Regi',115),
('Cocina','Cocineta, bodegas (3h)',array[4]::smallint[],'Late morning','Regi',118),
('Contenedor','Contenedor limpieza profunda',array[4]::smallint[],'Afternoon','Regi',220),
('The Ark House','The Ark House limpieza profunda (2h)',array[5]::smallint[],'Early morning','Regi',21),
('Cocina','Cocina limpieza profunda y baños, prender aire del container',array[5]::smallint[],'Late morning','Regi',122),
('The Shala','The Shala limpieza profunda',array[5]::smallint[],'Afternoon','Regi',223),
('The Ark House','The Ark House (2h)',array[0,2]::smallint[],'Early morning','Rosi',24),
('The Shala','Shala, general (1h)',array[0]::smallint[],'Late morning','Rosi',125),
('Padel','Paletas de padel',array[0]::smallint[],'Late morning','Rosi',126),
('Cocina','Cocina repaso (30 min)',array[0,2]::smallint[],'Late morning','Rosi',127),
('Baños','Baños y chequear deck',array[0]::smallint[],'Afternoon','Rosi',228),
('Arkadia','Arkadia (1.5h)',array[1,3,4]::smallint[],'Early morning','Rosi',29),
('Gym','Gym (30 min)',array[1,3]::smallint[],'Early morning','Rosi',30),
('The Shala','Shala general, limpieza pesas y deck (3h total)',array[1,3]::smallint[],'Late morning','Rosi',131),
('Cocina','Cocina (1h)',array[1,2,3]::smallint[],'Afternoon','Rosi',232),
('Deck','Deck limpieza profunda (2.5h)',array[2,4]::smallint[],'Late morning','Rosi',134),
('Cocina','Cocina (30 min)',array[3]::smallint[],'Late morning','Rosi',140),
('Baños','Baños',array[4]::smallint[],'Early morning','Rosi',43),
('The Ark House','Repaso Ark House (1h)',array[4]::smallint[],'Afternoon','Rosi',245),
('The Ark House','The Ark House limpieza profunda (2h)',array[5]::smallint[],'Early morning','Rosi',46),
('Cocina','Cocina limpieza profunda, baños',array[5]::smallint[],'Late morning','Rosi',147),
('Deck','Deck, repaso (30 min)',array[5]::smallint[],'Late morning','Rosi',148),
('The Shala','The Shala limpieza profunda',array[5]::smallint[],'Afternoon','Rosi',249),
('Contenedor','Contenedor AM (2h)',array[0,1]::smallint[],'Early morning','Daniela',50),
('Contenedor','Contenedor AM (1.5h)',array[2,3,4]::smallint[],'Early morning','Daniela',52),
('Baños','Baños (30 min)',array[0,1,2]::smallint[],'Early morning','Daniela',55),
('Beehive','Beehive',array[0]::smallint[],'Late morning','Daniela',158),
('Deck','Deck y baños',array[0]::smallint[],'Late morning','Daniela',159),
('Cocina','Cocina repaso',array[0]::smallint[],'Afternoon','Daniela',260),
('Beehive','Beehive chequeo general (3h)',array[1]::smallint[],'Late morning','Daniela',161),
('Beehive','Beehive (3h)',array[2]::smallint[],'Late morning','Daniela',162),
('Baños','Repaso baños (30 min)',array[2]::smallint[],'Late morning','Daniela',163),
('Baños','Repaso baños (1h)',array[2]::smallint[],'Afternoon','Daniela',264),
('Beehive','Beehive y deck (3h)',array[3]::smallint[],'Late morning','Daniela',165),
('Reception','A disposición',array[3,4]::smallint[],'Late morning','Daniela',166),
('Baños','Repaso baños (30 min)',array[3]::smallint[],'Afternoon','Daniela',267),
('Reception','Recepción limpieza profunda',array[4]::smallint[],'Late morning','Daniela',168),
('Contenedor','Contenedor limpieza profunda',array[4]::smallint[],'Afternoon','Daniela',270),
('Cocina','Baños, cocina (1.5h)',array[6]::smallint[],'Early morning','Daniela',71),
('Arkadia','Arkadia',array[6]::smallint[],'Late morning','Daniela',172),
('Baños','Baños repaso (30 min)',array[6]::smallint[],'Late morning','Daniela',173),
('Extras','Extras',array[6]::smallint[],'Afternoon','Daniela',274),
('Padel','Baños de padel y paletas (2h total)',array[0]::smallint[],'Late morning','Erika',175),
('Gym','Gym',array[0]::smallint[],'Late morning','Erika',176),
('Arkadia','Arkadia',array[0]::smallint[],'Afternoon','Erika',277),
('Padel','Baños de padel y limpiar paletas (2h)',array[1]::smallint[],'Late morning','Erika',178),
('Deck','Deck (1h)',array[1]::smallint[],'Late morning','Erika',179),
('Arkadia','Arkadia (4h)',array[1,2,3,4]::smallint[],'Afternoon','Erika',280),
('Padel','Baños de padel y raquetas (2.5h)',array[2,3,4]::smallint[],'Late morning','Erika',181),
('Gym','Gym (30 min)',array[2,3,4]::smallint[],'Late morning','Erika',182),
('Deck','Deck y gym (2h)',array[6]::smallint[],'Early morning','Erika',90),
('Arkadia','Arkadia',array[6]::smallint[],'Late morning','Erika',191),
('Padel','Baños padel',array[6]::smallint[],'Late morning','Erika',192),
('Extras','Extras',array[6]::smallint[],'Afternoon','Erika',293);
